export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const LOGOUT = "LOGOUT";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const UPDATE_USER_STARTING = "UPDATE_USER_STARTING";
export const SHOW_MODAL = "SHOW_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const UPDATE_FAVORITE = "UPDATE_FAVORITE";
export const UPDATE_WATCHLIST = "UPDATE_WATCHLIST";
