//redux
export const UPDATE_USER_STARTING = "UPDATE_USER_STARTING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const SHOW_MODAL = "SHOW_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const UPDATE_FAVORITE_STARTING = "UPDATE_FAVORITE_STARTING";
export const UPDATE_FAVORITE_SUCCESS = "UPDATE_FAVORITE_SUCCESS";
export const UPDATE_FAVORITE_ERROR = "UPDATE_FAVORITE_ERROR";
export const UPDATE_WATCHLIST_STARTING = "UPDATE_WATCHLIST_STARTING";
export const UPDATE_WATCHLIST_SUCCESS = "UPDATE_WATCHLIST_SUCCESS";
export const UPDATE_WATCHLIST_ERROR = "UPDATE_WATCHLIST_ERROR";
//saga
export const LOGOUT = "LOGOUT";
export const USER_AUTHENTICATION = "USER_AUTHENTICATION";
export const GET_INITIAL_USER_DATA = "GET_INITIAL_USER_DATA";
export const UPDATE_FAVORITE = "UPDATE_FAVORITE";
export const UPDATE_WATCHLIST = "UPDATE_WATCHLIST";
