export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const LOGOUT = "LOGOUT"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"
export const UPDATE_USER_STARTING = "UPDATE_USER_STARTING";